FROM openjdk:8
LABEL author = "venky" && Organaization = "Leo Marcom Pvt Ltd"
ADD : https://venkyashhu.s3.amazonaws.com/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar  /spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar
EXPOSE : 8090
CMD : ["java" "-jar" "/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar"]