apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
spec:
  replicas: 5
  selector:
    app: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins
          ports:
            - containerPort: 8080
              protocol: TCP
