apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 5
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: postgres
          ports:
            - containerPort: 8080
