---
- hosts : all
  become : yes
  tasks :
    - name : installing apache2 and updating apache2
      apt :
        name : apache2
        update_cache : yes
        state : present
    - name : restarting apache2
      service :
        name : apache2
        enabled : yes
        state : restarted
    - name : installing php
      apt :
        name : php
        state : present
    - name : installing libapache2-mod-php
      apt :
        name : libapache2-mod-php
        state : present
    - name : installing php-mysql
      apt :
        name : php-mysql
        state : present
    - name : installing php-cli
      apt : 
        name : php-cli
        state : present
    - name : restarting apache2
      service :
        name : apache2
        enabled : yes
        state : restarted

- hosts: all
  become : yes
  tasks :
    - name : installing httpd
      yum : 
        name : httpd
        state : present
        update_cache : yes
    - name : restarting httpd
      service :
        name : httpd
        enabled : yes
        state : restarted
    - name : installing php
      yum : 
        name : php
        state : present
    - name : installing php-mysql
      yum :
        name : php-mysql
        state : present
    - name : restart httpd
      service :
        name : httpd
        enabled : yes
        state : restarted